### ISSUE TITLE
Installation create wrong symlink to piper on Ubuntu 20.04

### ISSUE THREAD

**Issue by matrixik** [muzena/piper-packaging#3]
After installing piper same way like described in https://github.com/libratbag/piper/issues/515#issue-610916289 Ubuntu 20.04) I'm getting same error when trying to start `piper`: `ModuleNotFoundError`.

Turns out that following line is getting wrong python version:

https://github.com/muzena/piper-packaging/blob/9fa3f8f168ddc7bee71b89a54268a57dec93a1ad/debian/piper.postinst#L4

```
λ ll /usr/lib/python3/dist-packages/piper
lrwxrwxrwx 1 root root 39 2021-07-06 16:17:17 /usr/lib/python3/dist-packages/piper -> /usr/lib/python3.8./site-packages/piper
```
As you can see it's linking to `python3.8.` (with dot at the end).
```
λ python3 -V
Python 3.8.10
```

Workaround:
```
sudo ln -si /usr/lib/python3.8/site-packages/piper /usr/lib/python3/dist-packages/piper
```

**Comment by muzena** [comment]
@matrixik 
I think, now is fixed,try to install or upgrade.

**Comment by matrixik** [comment]
The update is still not working
```
λ echo 'python 3.8.10' | tail -c 7 | sed 's/ //' | cut -c-4 | sed -e 's/^[ \t]*//'
3.8.
```
I think something like this could work:
```
λ echo 'python 3.8.11' | cut -d' ' -f2 | sed -e 's/^[ \t]*//'
3.8.11
```

**Comment by matrixik** [comment]
Ups, sorry we need only `major.minor`
```
λ echo 'python 3.8.11' | cut -d' ' -f2 | sed -e 's/^[ \t]*//' | cut -d. -f1-2
3.8
```
I think that most secure way would be asking python directly:
```
λ python3 -c 'import platform; major, minor, patch = platform.python_version_tuple(); print(major + "." + minor)'
3.8
```
or
```
λ python3 -c 'import sys;  print(str(sys.version_info.major) + "." + str(sys.version_info.minor))'
3.8
```
or even
```
λ python3 -c 'import sys; print(".".join(map(str, sys.version_info[0:2])))'
3.8
```

**Comment by muzena** [comment]
@matrixik 
Try now I add to post installation script this:
python3 -c 'import sys; print(".".join(map(str, sys.version_info[0:2])))'

**Comment by matrixik** [comment]
I can confirm that after last update it's working properly. Thank you.
